<?php
$scope=current_branch_scope();$type=$_GET['movement']??'';$params=[];$where=['1=1'];
$voidReady=inventory_void_schema_ready();$canVoid=Auth::actorIsSystemAdmin()&&$voidReady;
if($scope){$where[]='sm.branch_id=:branch';$params['branch']=$scope;}
if(in_array($type,['stock_in','stock_out','sale','transfer_in','transfer_out','adjustment','return','defective'],true)){$where[]='sm.movement_type=:movement';$params['movement']=$type;}
$voidSelect=$voidReady?'v.id void_id,v.reason void_reason,va.name void_actor':'NULL void_id,NULL void_reason,NULL void_actor';
$voidJoin=$voidReady?'LEFT JOIN inventory_movement_voids v ON v.movement_id=sm.id LEFT JOIN users va ON va.id=v.voided_by':'';
$rows=[];
try{$rows=Database::query("SELECT sm.*,b.name branch_name,u.name user_name,COALESCE(NULLIF(iu.serial_no,''),NULLIF(iu.imei,''),p.barcode) identifier_value,iu.condition_type,COALESCE(CONCAT(br.name,' ',pm.name),p.product_name) product_label,p.ram,p.storage,p.connectivity,p.color,{$voidSelect} FROM stock_movements sm JOIN products p ON p.id=sm.product_id LEFT JOIN inventory_units iu ON iu.id=sm.unit_id JOIN branches b ON b.id=sm.branch_id JOIN users u ON u.id=sm.created_by LEFT JOIN brands br ON br.id=p.brand_id LEFT JOIN product_models pm ON pm.id=p.model_id {$voidJoin} WHERE ".implode(' AND ',$where)." ORDER BY sm.created_at DESC,sm.id DESC LIMIT 150",$params)->fetchAll();}catch(Throwable $e){Security::reportException($e,'stock_movement');}
function movement_specs(array $row):string{$parts=[];foreach(['ram','storage','connectivity','color'] as $key)if(!empty($row[$key]))$parts[]=$row[$key];if(($row['condition_type']??'')==='preloved')$parts[]='Pre-Loved';return implode(' • ',$parts);}
?>
<section class="page-heading"><div><span class="eyebrow">IN / OUT HISTORY</span><h1>Stock Movement</h1><p>Track stock in, stock out, transfers and adjustments with accountability.</p></div><?php if($canVoid): ?><button type="button" class="btn btn-outline" id="reviewInventoryVoid">Void Selected</button><?php endif; ?></section>
<?php if(Auth::actorIsSystemAdmin()&&!$voidReady): ?><div class="alert alert-error">Import <strong>database/P2_024_system_admin_inventory_void.sql</strong> into the existing POS database to enable Void.</div><?php endif; ?>
<div class="tab-row"><?php $tabs=[''=>'All','stock_in'=>'Stock In','stock_out'=>'Stock Out','sale'=>'Sold','transfer_out'=>'Transfer','adjustment'=>'Adjustment'];foreach($tabs as $key=>$label): $tabParams=[];if($scope)$tabParams['branch']=$scope;if($key)$tabParams['movement']=$key; ?><a class="tab <?= $type===$key?'active':'' ?>" href="<?= e(app_url('stock-movement',$tabParams)) ?>"><?= e($label) ?></a><?php endforeach; ?></div>
<?php if($canVoid): ?><p>Select only incorrect outgoing records, then <strong>Void Selected</strong>. Stock returns to the original branch shown below.</p><p id="inventoryVoidSelectionMessage" role="status"></p><?php endif; ?>
<section class="card table-card"><div class="table-wrap"><table class="data-table"><thead><tr><?php if($canVoid): ?><th>Select</th><?php endif; ?><th>Date</th><th>Item</th><th>Device ID / Barcode</th><th>Branch</th><th>Movement Type</th><th>Qty</th><th>Added By</th><th>Status</th></tr></thead><tbody>
<?php if(!$rows): ?><tr><td colspan="<?= $canVoid?9:8 ?>"><div class="empty-state"><strong>No movement history yet</strong></div></td></tr><?php else: foreach($rows as $row):$movement=$row['movement_type'];$eligible=!$row['void_id']&&(int)$row['quantity']<0&&in_array($movement,['sale','stock_out','adjustment','defective'],true); ?>
<tr><?php if($canVoid): ?><td><?php if($eligible): ?><input type="checkbox" data-inventory-void value="<?= (int)$row['id'] ?>" aria-label="Select <?= e($row['identifier_value']?:$row['product_label']) ?> for void" data-void-summary="<?= e(($row['identifier_value']?:$row['product_label']).' • '.$row['branch_name'].' • '.$row['reference_no'].' • '.abs((int)$row['quantity']).' unit(s)') ?>"><?php else: ?>—<?php endif; ?></td><?php endif; ?>
<td><strong><?= e(date('M d, Y',strtotime($row['created_at']))) ?></strong><span class="table-subtext"><?= e(date('h:i A',strtotime($row['created_at']))) ?><?= !empty($row['reference_no'])?' • '.e($row['reference_no']):'' ?></span></td><td><strong><?= e($row['product_label']) ?></strong><span class="table-subtext"><?= e(movement_specs($row)) ?></span></td><td class="mono"><?= e($row['identifier_value']?:'—') ?></td><td><?= e($row['branch_name']) ?></td><td><span class="movement-pill <?= e($movement) ?>"><?= e(movement_label($movement)) ?></span></td><td><strong class="<?= $row['quantity']>=0?'text-success':'text-danger' ?>"><?= $row['quantity']>=0?'+':'' ?><?= (int)$row['quantity'] ?></strong></td><td><?= e($row['user_name']) ?></td><td><?php if($row['void_id']): ?><span class="status-pill">Voided</span><span class="table-subtext"><?= e($row['void_actor']) ?> • <?= e($row['void_reason']) ?></span><?php else: ?><span class="status-pill completed">Completed</span><?php endif; ?><?php if(in_array($movement,['return','adjustment'],true)&&str_starts_with((string)$row['reference_no'],'VOID-')): ?><span class="table-subtext">Void restoration</span><?php endif; ?></td></tr><?php endforeach; endif; ?>
</tbody></table></div></section>
<?php if($canVoid): ?>
<div class="modal" id="inventoryVoidModal" hidden><div class="modal-backdrop" data-void-close></div><div class="modal-dialog" role="dialog" aria-modal="true" aria-labelledby="inventoryVoidTitle"><form method="post" action="actions/void_inventory_movement.php" id="inventoryVoidForm">
<input type="hidden" name="_csrf" value="<?= e(Csrf::token()) ?>"><input type="hidden" name="return_branch" value="<?= (int)$scope ?>"><input type="hidden" name="return_movement" value="<?= e($type) ?>"><div id="inventoryVoidIds"></div>
<div class="modal-header"><div><span class="eyebrow">SYSTEM ADMIN</span><h2 id="inventoryVoidTitle">Void Selected Records</h2></div><button type="button" class="icon-button" data-void-close aria-label="Close">×</button></div>
<div class="modal-body"><p>These exact records will be voided and their stock restored to the original branch. Other sale items remain unchanged.</p><ul id="inventoryVoidReview"></ul><label class="field"><span>Reason <b>*</b></span><textarea name="reason" minlength="3" maxlength="180" rows="3" required placeholder="Recorded as sold by mistake; units never left the branch."></textarea></label><p>This corrects inventory and recorded sales. Review any actual payment separately.</p></div>
<div class="modal-actions"><button type="button" class="btn btn-secondary" data-void-close>Cancel</button><button type="submit" class="btn btn-primary">Void &amp; Restore Selected</button></div></form></div></div>
<script src="assets/js/inventory-void.js?v=<?= (int)@filemtime(__DIR__.'/../assets/js/inventory-void.js') ?>"></script>
<?php endif; ?>