<?php
$scope=current_branch_scope();$type=$_GET['movement']??'';$params=[];$where=['1=1'];
if($scope){$where[]='sm.branch_id=:branch';$params['branch']=$scope;}
if(in_array($type,['stock_in','stock_out','sale','transfer_in','transfer_out','adjustment','return','defective'],true)){$where[]='sm.movement_type=:movement';$params['movement']=$type;}
$rows=[];
try{$rows=Database::query("SELECT sm.*,b.name branch_name,u.name user_name,COALESCE(iu.imei,iu.serial_no,p.barcode) identifier_value,iu.condition_type,COALESCE(CONCAT(br.name,' ',pm.name),p.product_name) product_label,p.ram,p.storage,p.connectivity,p.color FROM stock_movements sm JOIN products p ON p.id=sm.product_id LEFT JOIN inventory_units iu ON iu.id=sm.unit_id JOIN branches b ON b.id=sm.branch_id JOIN users u ON u.id=sm.created_by LEFT JOIN brands br ON br.id=p.brand_id LEFT JOIN product_models pm ON pm.id=p.model_id WHERE ".implode(' AND ',$where)." ORDER BY sm.created_at DESC LIMIT 150",$params)->fetchAll();}catch(Throwable $e){}
function movement_specs(array $row):string{$parts=[];foreach(['ram','storage','connectivity','color'] as $key)if(!empty($row[$key]))$parts[]=$row[$key];if(($row['condition_type']??'')==='preloved')$parts[]='Pre-Loved';return implode(' • ',$parts);}
?>
<section class="page-heading"><div><span class="eyebrow">IN / OUT HISTORY</span><h1>Stock Movement</h1><p>Track stock in, stock out, transfers and adjustments with accountability.</p></div></section>
<div class="tab-row"><?php $tabs=[''=>'All','stock_in'=>'Stock In','stock_out'=>'Stock Out','sale'=>'Sold','transfer_out'=>'Transfer','adjustment'=>'Adjustment'];foreach($tabs as $key=>$label): ?><a class="tab <?= $type===$key?'active':'' ?>" href="<?= e(owner_branch_filter_url('stock-movement',$scope)) ?><?= $key?'&movement='.$key:'' ?>"><?= e($label) ?></a><?php endforeach; ?></div>
<section class="card table-card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Item</th><th>Device ID / Barcode</th><th>Branch</th><th>Movement Type</th><th>Qty</th><th>Added By</th><th>Status</th></tr></thead><tbody>
<?php if(!$rows): ?><tr><td colspan="8"><div class="empty-state"><div class="empty-icon"><?= icon('movement') ?></div><strong>No movement history yet</strong><span>Stock activity will appear here automatically.</span></div></td></tr>
<?php else: foreach($rows as $row):$movement=$row['movement_type']; ?><tr><td><strong><?= e(date('M d, Y',strtotime($row['created_at']))) ?></strong><span class="table-subtext"><?= e(date('h:i A',strtotime($row['created_at']))) ?><?= !empty($row['reference_no'])?' • '.e($row['reference_no']):'' ?></span></td><td><strong><?= e($row['product_label']) ?></strong><span class="table-subtext"><?= e(movement_specs($row)) ?></span></td><td class="mono"><?= e($row['identifier_value']?:'—') ?></td><td><?= e($row['branch_name']) ?></td><td><span class="movement-pill <?= e($movement) ?>"><?= e(movement_label($movement)) ?></span></td><td><strong class="<?= $row['quantity']>=0?'text-success':'text-danger' ?>"><?= $row['quantity']>=0?'+':'' ?><?= (int)$row['quantity'] ?></strong></td><td><?= e($row['user_name']) ?></td><td><span class="status-pill completed">Completed</span></td></tr><?php endforeach; endif; ?>
</tbody></table></div></section>
