<?php
$q=trim((string)($_GET['q']??'')); $role=trim((string)($_GET['role']??'')); $branch=(int)($_GET['branch']??0); $status=(string)($_GET['status']??'active');
$where=["u.role<>'system_admin'"]; $params=[];
if($q!==''){ $where[]='(u.name LIKE :q_name OR u.email LIKE :q_email OR b.name LIKE :q_branch)'; $like='%'.$q.'%'; $params['q_name']=$like; $params['q_email']=$like; $params['q_branch']=$like; }
if(in_array($role,['owner','branch_manager','inventory','cashier'],true)){ $where[]='u.role=:role'; $params['role']=$role; }
if($branch>0){ $where[]='u.branch_id=:branch'; $params['branch']=$branch; }
if($status==='active')$where[]='u.is_active=1'; elseif($status==='inactive')$where[]='u.is_active=0';
$rows=[];$branches=[];
try{
$rows=Database::query("SELECT u.id,u.name,u.email,u.role,u.branch_id,u.is_active,u.must_change_password,COALESCE((SELECT MAX(sal.created_at) FROM security_audit_logs sal WHERE sal.event_type='auth.login_success' AND sal.user_id=u.id),u.last_login_at) AS last_login_at,b.name branch_name FROM users u LEFT JOIN branches b ON b.id=u.branch_id WHERE ".implode(' AND ',$where)." ORDER BY FIELD(u.role,'owner','branch_manager','inventory','cashier'),b.id,u.name",$params)->fetchAll();
$branches=Database::query('SELECT id,name FROM branches WHERE is_active=1 ORDER BY id')->fetchAll();
}catch(Throwable $e){Security::reportException($e,'system_admin_users');}
?>
<section class="page-heading"><div><span class="eyebrow">SYSTEM SUPPORT</span><h1>User Accounts</h1><p>Enter an active Owner or Branch account without knowing its password.</p></div></section>
<form class="card filter-card system-admin-filter" method="get" action="<?= e(app_url('system-admin-users')) ?>"><label class="search-box"><?= icon('search') ?><input name="q" value="<?= e($q) ?>" placeholder="Search name, email, branch…"></label><select name="role"><option value="">All Roles</option><?php foreach(['owner'=>'Owner','branch_manager'=>'Branch Manager','inventory'=>'Inventory Staff','cashier'=>'Cashier'] as $v=>$l):?><option value="<?= e($v) ?>" <?= $role===$v?'selected':'' ?>><?= e($l) ?></option><?php endforeach;?></select><select name="branch"><option value="0">All Branches</option><?php foreach($branches as $b):?><option value="<?= (int)$b['id'] ?>" <?= $branch===(int)$b['id']?'selected':'' ?>><?= e($b['name']) ?></option><?php endforeach;?></select><select name="status"><option value="active" <?= $status==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= $status==='inactive'?'selected':'' ?>>Inactive</option><option value="all" <?= $status==='all'?'selected':'' ?>>All Status</option></select><button class="btn btn-secondary" type="submit">Apply</button></form>
<section class="card table-card"><div class="card-header"><div><h2>Available Accounts</h2><p><?= count($rows) ?> account<?= count($rows)===1?'':'s' ?> in this view.</p></div><span class="security-note"><?= icon('shield') ?> Passwords stay private</span></div><div class="table-wrap"><table class="data-table system-admin-users-table"><thead><tr><th>User</th><th>Role</th><th>Branch</th><th>Status</th><th>Last Login</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td data-label="User"><strong><?= e($row['name']) ?></strong><span class="table-subtext"><?= e($row['email']) ?></span></td><td data-label="Role"><span class="user-role-pill role-<?= e($row['role']) ?>"><?= e(role_label($row['role'])) ?></span></td><td data-label="Branch"><?= e($row['branch_name']?:'All Branches') ?></td><td data-label="Status"><span class="status-pill <?= $row['is_active']?'available':'low' ?>"><?= $row['is_active']?'Active':'Inactive' ?></span><?php if((int)$row['must_change_password']===1):?><span class="status-pill user-password-pending">Password Change Required</span><?php endif;?></td><td data-label="Last Login"><?php if(!empty($row['last_login_at'])){ try{ $loginDt=new DateTimeImmutable((string)$row['last_login_at'],new DateTimeZone('Asia/Manila')); echo e($loginDt->format('M j, Y • g:i A')); }catch(Throwable $ignore){ echo e((string)$row['last_login_at']); } }else{ echo 'Never'; } ?></td><td data-label="Action"><?php if($row['is_active']):?><form method="post" action="actions/impersonation.php" data-confirm="Enter <?= e($row['name']) ?>'s account view?"><input type="hidden" name="_csrf" value="<?= e(Csrf::token()) ?>"><input type="hidden" name="action" value="start"><input type="hidden" name="target_user_id" value="<?= (int)$row['id'] ?>"><button class="btn btn-primary btn-sm" type="submit"><?= icon('eye') ?> Enter Account</button></form><?php else:?><button class="btn btn-secondary btn-sm" disabled>Inactive</button><?php endif;?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="6"><div class="empty-state small"><strong>No accounts found.</strong><span>Adjust the filters and try again.</span></div></td></tr><?php endif;?></tbody></table></div></section>
